Create new README for 1.0.0 version
jellyfin/jellyfin-sdk-kotlin pull request #193
Opened 2021-03-14 11:54 UTC by nielsvanvelzen

2021-03-19 02:56 UTC, thornbill reviewed
Looks great! Only one minor suggestion.

2021-03-19 02:56 UTC, thornbill commented on README.md
> +It is currently available for the JVM and Android targets.
```suggestion
It is currently available for the JVM and Android platforms.
```

2021-03-22 21:02 UTC, nielsvanvelzen commented on README.md
> +<img alt="Bintray Release" src="https://img.shields.io/bintray/v/jellyfin/jellyfin-sdk-kotlin/jellyfin-sdk-kotlin.svg"/>
Replacing it with a maven badge

2021-03-22 21:04 UTC, nielsvanvelzen commented on README.md
> +println(authenticationResult.accessToken)
Changed it to not print access token

2021-03-22 21:09 UTC, nielsvanvelzen commented
Thanks for the thorough review @Maxr1998, I noticed some lines still using the "api client" term so I updated those as well.

2021-03-22 21:31 UTC, Maxr1998 requested changes

2021-03-22 21:31 UTC, Maxr1998 commented on README.md
> +<img alt="Bintray Release" src="https://img.shields.io/maven-central/v/org.jellyfin.sdk/jellyfin-core.svg"/>
```suggestion
<img alt="Maven Release" src="https://img.shields.io/maven-central/v/org.jellyfin.sdk/jellyfin-core.svg"/>
```

:eyes:

2021-03-22 21:31 UTC, nielsvanvelzen commented on README.md
> +<img alt="Bintray Release" src="https://img.shields.io/maven-central/v/org.jellyfin.sdk/jellyfin-core.svg"/>
I'm stupid

2021-03-22 21:34 UTC, Maxr1998 approved these changes

2021-03-22 21:35 UTC, merged